=== Tartori/OOP/OOPMarc/xml.xsd.addressNamespace.sol/src/address_tns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Address schema with target namespace for AddressSchema-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" 
	targetNamespace="http://www.bfh.ch/AddressSchema" 
	xmlns="http://www.bfh.ch/AddressSchema"	>
	
		<xsd:complexType name="address_type">
			<xsd:sequence>
				<xsd:element name="firstname" type="xsd:string" />
				<xsd:element name="name" type="xsd:string" />
				<xsd:element name="title" type="xsd:string" />
				<xsd:element name="street" type="xsd:string" />
				<xsd:element name="number" type="xsd:integer" />
				<xsd:element name="apt-number" type="xsd:string" />
				<xsd:element name="city" type="xsd:string" />
				<xsd:element name="zip" type="xsd:integer" />
				<xsd:element name="country" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	
	<xsd:element name="address" type="address_type"/>
</xsd:schema>

=== Tartori/OOP/OOPMarc/xml.xsd.addressNamespace.sol/src/address_xsd_tns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Address xml with target namespace for AddressSchema -->
<address xmlns="http://www.bfh.ch/AddressSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bfh.ch/AddressSchema
                         ./address_tns.xsd">
	<firstname>John</firstname>
	<name>Smith</name>
	<title>Master of Arts</title>
	<street>45th Avenue</street>
	<number>12</number>
	<apt-number>15</apt-number>
	<city>New York</city>
	<zip>10003</zip>
	<country>USA</country>
</address>

=== Tartori/OOP/OOPMarc/xml.xsd.addressNamespace.sol/src/address_xsd_tns2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- address xml without default target namespace-->
<adr:address xmlns:adr="http://www.bfh.ch/AddressSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bfh.ch/AddressSchema
                         ./address_tns.xsd">
	<adr:firstname>John</adr:firstname>
	<adr:name>Smith</adr:name>
	<adr:title>Master of Arts</adr:title>
	<adr:street>45th Avenue</adr:street>
	<adr:number>12</adr:number>
	<adr:apt-number>15</adr:apt-number>
	<adr:city>New York</adr:city>
	<adr:zip>10003</adr:zip>
	<adr:country>USA</adr:country>
</adr:address>
