=== Tartori/OOP/OOP/out/production/XmlModule/Exam1/Task1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- address xml without namespaces -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:simpleType name="summaryType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="yes|no"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="project">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="target" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="javac">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="classpath"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="destdir" type="xsd:string"/>
                                    <xsd:attribute name="srcdir" type="xsd:string"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="junit">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="classpath"/>
                                        <xsd:element name="test" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="printsummary" type="summaryType"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Tartori/OOP/OOP/XmlModule/src/Exam1/Task.xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="Packaging" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Task1.xsd">
    <!-- Ein project-Element kann beliebig viele target-Elemente enthalten ( 1..n )  -->
    <target name="test">
        <javac destdir="${test.dir}" srcdir="${test.src}">
            <classpath> test.classpath </classpath>
        </javac>
        <!-- Attribute printsummery hat nur die Werte yes oder no -->
        <junit printsummary="yes">
            <classpath> test.classpath </classpath>
            <!-- Ein junit-Element kann beliebig viele test-Elemente enthalten ( 1..n )  -->
            <!-- Das name-attribute des test-Elementes ist obligatorisch -->
            <test name="workbench.FileAccessTest" />

        </junit>
    </target>
    <target name="test">
        <javac destdir="${test.dir}" srcdir="${test.src}">
            <classpath> test.classpath </classpath>
        </javac>
        <!-- Attribute printsummery hat nur die Werte yes oder no -->
        <junit printsummary="yes">
            <classpath> test.classpath </classpath>
            <!-- Ein junit-Element kann beliebig viele test-Elemente enthalten ( 1..n )  -->
            <!-- Das name-attribute des test-Elementes ist obligatorisch -->
            <test name="workbench.FileAccessTest" />
            <test name="workbench.FileDeleteTest" />
        </junit>
    </target>
</project>
